@startuml

class Animal {
  +hacerSonido(): void
}

class Perro {
  +hacerSonido(): void
}

class Gato {
  +hacerSonido(): void
}

class Robot {
  +moverse(): void
}

class Veterinario {
  +revisarAnimal(animal: Animal): void
}

Animal <|-- Perro
Animal <|-- Gato

@enduml
